#+TITLE:Key Analyzer

* TOC :toc:
- [[#about][About]]
- [[#install][Install]]
- [[#usage][Usage]]
  - [[#actions][Actions]]
  - [[#list-of-layouts][List of Layouts]]
  - [[#flags][Flags]]

* About
This is an experimental keyboard layout generator. It's quite work in
progress. Despite its current state, it can make keyboard layouts that
are quite good. From analysis of [[https:github.com/stevep][Steve P]]'s keyboard layout analyzer, a
much more mature project, the layouts generated have consistently
beaten layouts from Carpalx, as well as beating the layouts Dvorak,
Workman, and obviously Qwerty, while rivaling that of Colemak.
* Install
#+begin_src bash
    git clone https://github.com/semilin/key-analyzer
    cd key-analyzer
    go build
#+end_src

* Usage
=./keyanalyzer [action] [argument] -{flags}=

** Actions
*** Analyze
Gives a very basic analysis of a keyboard layout. This is not very
useful at the moment, but it does allow you to see a ranking of
different layouts.
*** Improve
Does a greedy improvement of the given layout.
*** Generate
Generates a keyboard layout through the process of simulated annealing
**** Altermak
Finds the keyboard layout with the highest alternation possible
**** Onehand (VERY WIP)
A very experimental project to find the best layout using only one
hand, employing the use of layers to hit the extra keys.
** List of Layouts
+ Qwerty
+ [[https:en.wikipedia.org/wiki/Dvorak_keyboard_layout][Dvorak]]
+ [[https:colemak.com][Colemak]]
+ [[https:colemakmods.github.io/mod-dh/][Colemak-DH]]
+ Hirou (by Nyfee)
  + I think that this is an older version, but I don't know what the
    new version looks like, and I'm not that bothered to update it.
+ [[https:github.com/MadRabbit/halmak][Halmak]]
** Flags
*NONE OF THESE ARE FUNCTIONAL AT THE MOMENT*
*** SFB Cost
=-sfb [int]=
*** Outward Roll Cost
=-outwardroll [int]=
*** Restrict
=-restrict [arg]=
+ none
+ hand
+ finger
